language: haskell
before_install: 
install:
- travis_retry cabal install pandoc pandoc-citeproc
- travis_retry bundle install
script:
- echo -e $twitter > _twitter.yml
- echo -e $twitter2 >> _twitter.yml
- echo -e $twitter3 >> _twitter.yml
- echo -e $garb > _garb.yml
- echo -e $garb2 >> _garb.yml
- bundle exec rake site:deploy
- wc _twitter.yml
- rm _twitter.yml _garb.yml
env:
  global:
  - secure: VsIGjVbcGVsuNwTFOcnndTzxlpIoOp3x5HyMQ+9CiTKGg6rsSAZihMunOXp4woI6Tj/1uT339onTq0saf5+3QEcUR2OcGz+lo6M/4AW2rkcG8rpu8kWN4OzLR1Qn5vYzpkg2/HbdSA9aZDta6bmw8jkitMt3UyRZj/LX/MRM6mo=
  - secure: Kz9DtwcEfan+1ErebbhadsQ/DEukPCI9orVyOzmpvABEx4Ur6jLYdt79Q/GEQPugggUNBs9XERmOx/wx/KJSvw/2VdoRaXskAWk66F6uOadYbrTYYZ95UJpv4X8cin21MSYOKLBeIJkZuX5PYUZg3FAGi7FUIu+UuUDNE7+lHaw=
  - secure: nMlkJXkMRwcAWceb7/o4pwDP1A+VeVRUVoaCoCIk11621ROMw3a5VHyum6kNEAla+9Ce970+xCNAdTIKuuLw7HjLsyGBiBQhMWDyNof4su5zayBh+sB2S/RXI8117eLQg0HLvIltOvwT9obphAfn4AkEWeZ1yApEzjVjK4rhzgU=
  - secure: QqrejLFqsAWc72l367h3U8cv6BKiOyxlxVrTm+4rsJeJiAuTlvKeFh8ZprbBeOTE3CuwjuDhUnbkkHbuUP6lgKb9A32pBGZyabI4eow/djvT22aUFMmIVaL+RQgICRpHsZ/k/SWrQlizls2YvQ/8PaVb86dcI2YC7DF1nYr2kS8=
  - secure: aTL4r19Wu2xj7e7Uvvm910xGRm8KYOfhEDhRsT/SLT8qbkF2gYqFJYR/jNI2WYUbMrbIRh5sA/iE4eQmJBvk4djf6zSfazFIzGcnSjeVUnzXgJuerJ2M2PGI2o/cWWmVMe4VD2WCMZbT9AjdJ944CcN6jPYpE3X9Km7fnt6IqdA=
  - secure: dcTeePa27wUo184towzeFTAOWoPtdXxklrHBxZxoxGLp9wVfc2oglOmhLZwFv6s6mq+ADEK3JlfewM4Kxmclwr6a4/e1Cf5V4nhbSvTCPkrmx8CXgoNxAWlHSDwJEDruc6kQdELsYOgQWT3lm6brjxB0dGUZDJUGoGfYEdefq1Q=
