## Useful metadata, available to a liquid filter as site.title, site.author.name, etc 
title: Lab Notebook 
tagline: Theoretical ecology and evolution
author:
  name: Carl Boettiger
  email: cboettig@gmail.com
  givenName: Carl
  familyName: Boettiger
  twitter: cboettig
  github: cboettig
  mendeley: carl-boettiger
keywords: Science, Ecology, Evolution, Open Science, Reproducible Research
description: My open lab notebook- research in theoretical ecology and evolution

url: http://www.carlboettiger.info
repo: https://github.com/cboettig/labnotebook # used in linking history
analytics: UA-18401403-1 

# toggle on sidebar pageviews -- can take a long time for a large site 
sidebar_pagviews: true

## Functional configuration 
permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/, assets/figures]

markdown: pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
#    - mathml            # Use mathml for equations (Archival, HTML5/XML valid syntax)
#    - self-contained    # Archive images in posts as URIs.  Very slow, for archiving only.  

#markdown: redcarpet2
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
