
title: Lab Notebook 
tagline: Theoretical ecology and evolution
author:
  name: Carl Boettiger
  givenName: Carl
  familyName: Boettiger
  twitter: cboettig
  github: cboettig
  mendeley: carl-boettiger
  email: cboettig@gmail.com
url: http://carlboettiger.info

# Github username (for travis/rake tasks, standard use)
username: cboettig
repo: labnotebook 

destination: ../cboettig.github.com

## Markdown Parser 
markdown: pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
#    - template: 'assets/datauri_template.html'   # Use with 'self-contained' to avoid header text in body
#    - self-contained                             # Archive images in posts as URIs.  Very slow, for archiving only.  
#    - mathml                                     # Use mathml for equations (Archival, HTML5/XML valid syntax)


permalink: /:year/:month/:day/:title.html
redirects: yes     ## A flag to turn on the redirects plugin
pageviews: no    ## toggle on sidebar pageviews 
twitter_api: yes
analytics: UA-18401403-1 ## Google Analytics key (in _includes/analytics.html)


exclude: 
  - _posts/source/
  - assets/figures
  - _garb.yml
  - _twitter.yml


