
title: Lab Notebook 
tagline: Theoretical ecology and evolution
author:
  name: Carl Boettiger
  givenName: Carl
  familyName: Boettiger
  twitter: cboettig
  github: cboettig
  mendeley: carl-boettiger
  email: cboettig@gmail.com
url: http://www.carlboettiger.info

baseurl: /
repo: cboettig.github.io

gems:
  - jekyll-pandoc
encoding: utf-8

sass:
  sass_dir: _sass
  style: compressed

## Markdown Parser 
markdown: pandoc
markdown_ext:  markdown,md
pandoc:
  extensions: 
    - smart
    - mathjax
    - email-obfuscation: javascript

permalink: /:year/:month/:day/:title.html
redirects: yes     ## A flag to turn on the redirects plugin
pageviews: no    ## toggle on sidebar pageviews 
twitter_api: yes
analytics: UA-18401403-1 ## Google Analytics key (in _includes/analytics.html)

exclude:
  - .drone.yml

# For local jekyll serve
host: 0.0.0.0


## Have pages & posts use their default layouts, respectively
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

